move_group:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1

ompl:
  planning_pipelines:
    - ompl

  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
      range: 0.3

  arm:
    planner_configs:
      - RRTConnect
